name: live_face_tracker
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2+1
  google_mlkit_face_detection: ^0.13.1
  image: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
